### ISSUE TITLE
Баг смайлов на форуме

### ISSUE THREAD

**Issue by Xmk** [Chiliec/lsplugin-emoji#3]
Смайлы не работают на форуме по 1 простой причине.
Плагин forum загружается **после** плагина emoji
Соответственно функции настроек редактора не переопределяются.
1 маленький костылек может очень просто решить эту проблему:
Условие

``` javascript
if(ls.forum !== undefined) {
```

обернуть в

``` javascript
jQuery(document).ready(function($){
```

Меня уже просто одолели с этой адаптиацией) пул делать честно лень.

**Добра, чел.**

**Comment by chiliec** [comment]
Спасибо, не знал о такой проблеме. Сделаю в ближайшее время.

**Comment by chiliec** [comment]
Беглое тестирование показало, что проблему это не решает. Может я чего-то не понимаю. Тем не менее, и сейчас всё хорошо работает, надо лишь чтобы `forum` стоял **перед** `emoji` в `plugins.dat` :)

**Comment by chiliec** [comment]
Будем считать что так оно и есть.
